spring:
  application:
    name: credit_processing
  datasource:
    url: jdbc:postgresql://localhost:5432/credit_db
    username: postgres
    password: 731
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hw2-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

credit:
  limit: 1000000

CLIENT_PROCESSING_URL:
  url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info