services:
  # ---------- INFRA ----------
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=hw2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=731
      - POSTGRES_MULTIPLE_DATABASES=client_db,account_db,credit_db
    ports:
      - "5432:5432"
    volumes:
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh

  # ---------- MICROSERVICES ----------
  client-processing:
    build:
      context: ./client_processing
      dockerfile: Dockerfile
    container_name: client-processing
    depends_on:
      - kafka
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/client_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=731
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8081:8080"
    restart: on-failure

  account-processing:
    build:
      context: ./account_processing
      dockerfile: Dockerfile
    container_name: account-processing
    depends_on:
      - kafka
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/account_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=731
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8082:8080"
    restart: on-failure

  credit-processing:
    build:
      context: ./credit_processing
      dockerfile: Dockerfile
    container_name: credit-processing
    depends_on:
      - kafka
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker,debug
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/credit_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=731
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - CLIENT_PROCESSING_URL.url=http://client-processing:8080
      - JAVA_OPTS=-Ddebug=true
    ports:
      - "8083:8080"
    restart: on-failure